server:
  port: 9087
spring:
  application:
    name: news-consumer
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: news-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379
      timeout: 5s